name: Swift
on: [push]
jobs:

  macos:
    name: macOS
    runs-on: macos-latest
    steps:
    - name: Install Swift
      uses: slashmo/install-swift@v0.3.0
      with:
        version: 5.7.1
    - name: Checkout
      uses: actions/checkout@v2
    - name: Swift Version
      run: swift --version
    - name: Test (Debug)
      run: ./build.sh
  
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - name: Install Swift
      uses: slashmo/install-swift@v0.3.0
      with:
        version: 5.7.1
    - name: Checkout
      uses: actions/checkout@v2
    - name: Swift Version
      run: swift --version
    - name: Test (Debug)
      run: ./build.sh
