name: Swift ARM
on: [push]
jobs:

    linux-armv7-crosscompile-build:
        name: Crosscompile for Linux Armv7
        runs-on: ubuntu-latest
        container: colemancda/swift-armv7:latest-prebuilt
        steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Swift Version
          run: swift --version
        - name: Install dependencies
          run: apt update && apt install cargo -y
        - name: Build (Debug)
          run: |
            export CARGO_BUILD_TARGET=armv7-unknown-linux-gnueabihf
            cargo fetch
            mkdir -p .build/plugins/outputs/swift-rust-example/SwiftRustExample/RustPlugin/cargo-build/
            cp -rf ~/.cargo/*  .build/plugins/outputs/swift-rust-example/SwiftRustExample/RustPlugin/cargo-build/
            cd $SRC_ROOT
            export SWIFT_PACKAGE_SRCDIR=$GITHUB_WORKSPACE
            export SWIFT_PACKAGE_BUILDDIR=$SWIFT_PACKAGE_SRCDIR/.build
            export SWIFTPM_CONFIGURATION=debug
            $SRC_ROOT/build-swift-package.sh
        - name: Archive Build artifacts
          uses: actions/upload-artifact@v3
          with:
            name: linux-armv7-crosscompile-test
            path: .build/*/*.xctest
    
    linux-armv7-crosscompile-test:
        name: Test for Linux Armv7
        runs-on: [self-hosted, Linux, ARM]
        container: colemancda/swift-armv7:latest-runtime
        needs: linux-armv7-crosscompile-build
        steps:
        - name: Download artifacts
          uses: actions/download-artifact@v3
          with: 
            name: linux-armv7-crosscompile-test
        - name: Test (Release)
          run: |
            chmod +x ./release/SwiftRustExamplePackageTests.xctest
            ./release/SwiftRustExamplePackageTests.xctest
