name: Swift
on: [push]
jobs:

  macos:
    name: macOS
    runs-on: macos-latest
    steps:
    - name: Install Swift
      uses: slashmo/install-swift@v0.3.0
      with:
        version: 5.7.1
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: cargo build; swift build --build-tests
    - name: Test
      run: swift test
  
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: ./build.sh
    - name: Test
      run: swift test
